import type { NextPage } from "next";
import { Container, Grid, Text } from "@nextui-org/react";
import styles from "../styles/Home.module.css";
import { Fragment } from "react";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>FOSS4G Thailand | Replica GeoJson.io</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid.Container gap={0} css={{ height: "100vh" }}>
        <Grid xs={8}>
          <Container>
            <Text
              h1
              size={60}
              css={{
                textGradient: "45deg, $blue600 -20%, $pink600 50%",
              }}
              weight="bold"
            >
              Let's
            </Text>
            <Text
              h1
              size={60}
              css={{
                textGradient: "45deg, $purple600 -20%, $pink600 100%",
              }}
              weight="bold"
            >
              Make the Web
            </Text>
            <Text
              h1
              size={60}
              css={{
                textGradient: "45deg, $yellow600 -20%, $red600 100%",
              }}
              weight="bold"
            >
              Prettier
            </Text>
          </Container>
        </Grid>
        <Grid xs={4}>
          <Container>
            <Text h1>
              {"Almost before we knew it, we had left the ground."}
            </Text>
          </Container>
        </Grid>
      </Grid.Container>
    </>
  );
};

export default Home;
